select common, sci_name, cdfgsp, recfinsp 
from luspecies where common like 'brown rockf%' 
or common like 'blue rock%'
or common like 'deacon rock%'
or common like 'vermilion rock%'
or common like 'gopher rock%'
or common like 'black and yellow rock%'
or common like 'China rock%'
or common like 'lingcod rock%'
or common like 'copper rock%'
or common like 'greenspotted rock%'
or common like 'black rock%'
or common like 'quillback rock%'
or common like 'rosy rock%'
or common like 'starry rock%'
or common like 'yellowtail rock%'
or common like 'olive rock%'
