---
title: Comparison of indices of relative abundance from recreational fishery-dependent surveys
author:
  - name: Melissa Hedges Monk
    email: melissa.monk@noaa.gov
    affiliation: Southwest Fisheries Science Center
  - name: Rebecca R. Miller
    email: rebecca.miller@noaa.gov
    affiliation: University of California Santa Cruz
  - name: E.J. Dick
    email: edward.dick@noaa.gov
    affiliation: Another University
  - name: Derek Zoolander
    email: derek@example.com
    affiliation: Southwest Fisheries Science Center
address:
  - code: Southwest Fisheries Science Center
    address: Fisheries Ecology Division, Southwest Fisheries Science Center, National Marine Fisheries Service, NOAA, 110 McAllister Way, Santa Cruz, CA 95066
  - code: University of California Santa Cruz
    address: Department, Street, City, State, Zip
    text: "Equal contribution"
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Fisheries Research"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

Introduction
============

Fisheries stock assessments rely on a wide range of data to model a population to fully understand the dynamics.  When fishery-independent data are not available, assessors try to make best used of the best available data, which may often only include fishery-dependent data. The West Coast groundfish Fishery Management Plan (FMP) includes 64 rockfish species, ___ of which do not have full stock assessments. 
Fisheries survey and catch data are used to develop standardized indices of abundance that inform fisheries stock assessment models [@Maunder2004]. Catch per unit effort (CPUE) is a common metric collected from fishery-dependent or fishery-independent surveys, with the latter providing unbiased data. However, fishery-independent surveys can be costly, labor intensive and often require a long time series to be considered informative in fisheries stock assessments.
Advantages of fishery-dependent data is  that it is collected directly from the the fishery whose operations are not constrained by sampling designs, but dependent on the behaviors of the captain and, in the case of recreational trips, customer preference. Fishery-dependent are only collected from areas legally open areas can be collected, i.e., areas closed to fishing are not sampled.  In California, this includes a network of marine protected areas (MPAs), rockfish conservation areas (RCAs) developed based on depth closures, and varying seasonal and depth closures that vary temporally and spatially along California’s coastline. Fishery-independent surveys are conducted using a scientific study design and, depending on the study, are not always confined to the same regulations as the commercial and recreational fishing sectors.  In an ideal situation, both fishery-dependent and fishery-independent surveys would used to inform the stock assessment model.

Depending on the stock assessment model and the available data for the fish stock, the index can have large influence on the assessment results (find examples). 

There are only two long-term fishery-independent surveys that span the U.S. West Coast that survey groundfish populations and neither are informative for nearshore rockfish species. The National Marine Fisheries Service Southwest Fisheries Science center conducts a juvenile rockfish and ecosystem survey using a midwater trawl and the West Coast Bottomfish Trawl (WCGBT) survey utilizes a xxx trawl to sample groundfish populations deeper than 55 m.  However, many of the important rockfish species inhabit untrawlable habitat and in depths shallower than the 55 m sampled by the WCGBT survey. The California Collaborative Fisheries Research Program (CCFRP), a fishery-independent hook-and-line survey, was designed to monitor California's network of Marine Protected Areas. The CCFRP was limited to the central coast of California from 2007-2016, and expanded to cover the entire California coast in 2017.  Indices of abundance developed from this program have informed nearshore rockfish stock assessments in recent years [@Monk2019; @Monk2021]. The CCFRP is not without its limitations in terms of spatial coverage and  


An index of relative abundance assumes that changes in the index are proportional to changes of  abundance in the population, which does not always hold or may not be linear [@Harley2001].


Along the U.S. West Coast, even if the stock assessment is categorized as data rich, oftentimes the the only index of abundance available is from a fishery-dependent CPUE time series of observed recreational angler catch rates [@Cope2013].  

There is currently no coastwide fishery-independent survey for the nearshore fisheries on the West Coast.  The National Marine Fisheries Service (NMFS) conducts an annual trawl survey, but the survey extends to a minimum depth of ___ (cite) and is known not to select for all rockfish species due to the inability to trawl in rocky habitats.  Several scientists are developing methods to survey untrawlable habitat and small areas of fishery-independent survey work are available. Propose survey methods include the use of stereo video landers (cite), acoustic surveys (cite), remotely operated vehicles (ROVs), as well as hook and line surveys. There are three ongoing hook and line surveys on the West Coast, two of which were designed to monitor MPA networks in central California (CCFRP) and Oregon (ODFW Marine Reserves Program).  T

In California, approximately 70% of the recreational fishing effort is in the SCB, and since the survey effort distributed proportional to effort, there are a large number of fishery-dependent data available for the SCB that overlap with the NWFSC hook and line survey fixed stations.

This data series is part of the onboard observer program, which collects location- and species-specific CPUE information for the recreational fishing fleet (Monk et al. 2014)

Fishery-dependent surveys sample the fishing fleets and are subject to potential sampling biases.  The sampling is dependent on the fishing boat’s behavior, which is to maximize catch.  Sampling of the fishing fleet is often opportunistic based on the availability of samplers and the availability of trips to sample.  Sampling the fisheries can also be constrained to the current regulations, which may prohibit the retention of a species or fishing at certain depths, i.e., California Department of Fish and Wildlife has varying spatial and temporal depth and season closures implemented through six management regions.  There is also a fairly new network of Marine Protected Areas (MPAs) designated from 2007-2012 that prohibit recreational fishing, and are therefore areas no longer sampled by the recreational fishing fleet.  However, the advantage to fishery-dependent sampling the reduced program cost compared to a more intensive scientific fishery-independent survey.




Fishing effort directed toward a specific species or species complex 

Angler interviews  

This paper focuses on methods to determine the appropriate trips to represent effort and the resulting indices of relative abundance from CDFW surveys of the recreational fleet.  The CDFW conducts two surveys of the CPFV fleet, and the same vessel may be sampled for each survey.





Assume fishing behavior is remains the same when observers are no onboard the vessel.


Methods
============

We explored trends in relative abundance for ___ rockfish from two surveys in the SCB, a fishery-independent hook and line survey and a fishery-depended onboard observer survey.  The NMFS Northwest Fishery Science Center conducted the fishery-independent hook and line survey (NWFSC hook and line survey) targeting shelf rockfish annually starting in 2004; we use data through 2014 (survey details documented in Harms et al. 2008).  The NWFSC hook and line survey design contains 196 fixed-station sites (which increased over time from the original 120 sites)  within 20 sampling areas (include figure?).  The sampling areas and fixed stations were positioned after discussions with the fishing community and include known rockfish fishing grounds.  The number of survey sites within a sampling area was proportional to the available rockfish habitat within the sampling area.  Sites were randomly selected ……..A site was sampled in a single visit, once per survey year and five concurrent drops were made at each sampled site. The survey chartered two commercial passenger fishing vessels (CPFV), which also participate in the recreational sportfishing fishery contributing data to the fishery-dependent survey.  All anglers were scientific personnel(?) fishing with five-hook sampling rigs (see Figure 2 in Harms….).  A a sampling site, the captain was allowed to search within 100-yard radius of the fixed-site location’s coordinates for the fishing drop.  The captain could reposition the boat for each of the five fishing drops at a site, as long as the start location is within the 100-yard radius.  The maximum soak time for a drop was five minutes, and an individual angler could reel up sooner, prior to the five minute maximum.  The hook dispositions (fish identified to species if caught) and soak time were recorded for the individual angler.   All rockfish species were retained for biological sampling (otolith and fin clips) and non-rockfish species were released when possible.

The California Department of Fish and Wildlife (CDFW) has conducted fishery-dependent onboard observer survey of the Commercial Passenger Fishing Vessel (CPFV or party/charter boat) fleet since 1999 (onboard observer survey).  Groundfish-targeted CPFV trips were sampled opportunistically (CPFV participation is voluntary) and sampling effort was distributed in proportion to fishing effort.  During a fishing trip the observer recorded information at each fishing drop.  Just prior to the start of each fishing drop, the sampler selected a subset of anglers to observe.  The sampler recorded all fish encountered (retained and discarded) by the subset of anglers as a group.  Samplers also recorded the time fished (starting when the captain announced “Lines down” to when the captain instructed anglers to reel lines up), GPS coordinates of the fishing drop (start and/or end latitude/longitude), and bottom depth.  The catch and fishing time of an individual angler were not recorded.  These data were used to create indices of abundance for the  _____ stock assessment of _______ and the 2013 and 2015 stock assessments.  In 2000, CDFW implemented fishing gear regulations of 3-hooks per line and one-line maximum per angler, and that changed to a 2-hook per line and one-line maximum in 2001.  We begin analyses of the onboard observer data in 2000 to reduce any bias introduced from these changes.   Spatial management and depth closures did not begin until 2004.


Standardized indices of abundance were generated for each survey and the data selection process was completed for each species individually.  A common phenomenon of ecological data is the high proportion of zero observations across samples and the question as to whether the sampling occurred within the species’ habitat and the species was not observed or if the sampling occurred outside of the species’ habitat (structural zeroes).  Fisheries survey data are often subset to exclude structural zeroes using the Stephens-MacCall method, which looks at the species composition of co-occurring species.  However, the onboard observer survey collected location-specific information on each observer fish encounter.  To subset the onboard observer survey data and exclude structural zeroes, we used the positive catch locations as a proxy for suitable habitat.  For a given species, we plotted drop locations of positive encounters created α-shapes (cite).  An α-shape is a generalization of a convex hull where α controls the detail of the shape, with an α of 0 returns the original points and alpha of ∞ returns the convex hull.  We specified the α-shape so that the area surrounding a single fishing drop had a radius of 0.01 decimal degree (corresponding to an ellipsoid area of  3.22km2) in ArcGIS using the buffer tool in the analysis toolbox.  Alpha-shapes intersecting land were cropped.  An example of the resulting α-shapes is in Figure xx (location and species descriptors were removed to protect confidentiality).  Fishing drops that did not intersect with an α-shape were considered structural zeroes, i.e., outside of the species’ habitat, and excluded from analyses.  



To ensure that we were using data from both surveys from the same areas, we filtered both datasets.  To determine which NWFSC hook and line survey sites and α-shapes to retain for a given species, we looked at the distribution of distances hook and line survey sites to the nearest α-shape.  Xxxxx.  NWFSC hook and line survey sites within 2 km of an α-shape were retained.  While high resolution habitat maps are not consistently available for the entire SCB, other work has shown the α-shape method to be a reasonable proxy for hard rocky habitat (Melissa Monk, unpublished data).


 Neither the NWFSC hook and line survey nor the onboard survey data used to develop the indices encompass the entire range of the species.  However, the point of the exercise is to compare the two methods and these surveys are sampling the same habitats in the SCB.
We explored the possibility of area-weighted indices, using the area of the α-shapes as the weighting scheme.  Neighboring α-shapes were aggregated to increase sample sizes.  

The onboard observer data were analyzed using the delta method with two generalized linear models (delta-GLM).  The first GLM models the probability of encountering the species of interest with a binomial likelihood and a logit link function.  The second GLM models the positive encounters with either gamma or lognormal errors structure.

Composition data from recreational surveys had the largest impact on simulation results, but individual survey components did not have individual effects on benchmarks (Siegfried et al. 2016).  
The onboard observer surveys decrease the amount of uncertainty, but relative to a fishery-independent survey, is still high…. 



#### Habitat
Reef Delineation We identified reefs as potential habitat for China rockfish in California, Oregon and Washington using a variety of newly available spatial data sources, including 2, 3 and 5 m bathymetry, substrate, lithology and Habitat Suitability geodatabases. Available data sources varied by latitude. To delineate reefs from Point Conception to the Oregon border we used a 2 m binary raster layer (3 m for Cordell Bank) for substrate, where 1 = rough, and 0 = smooth habitat (California Seafloor Mapping Project “Tier 2” GIS Products, accessed 03.18.2013, data available from: http://seafloor.otterlabs.org/index.html). Rough and smooth substrate was identified by CSMP using 2 rugosity indices based upon bathymetric data, surface:planar area (SA:PA), and vector ruggedness measure (VRM). We considered areas identified as ‘rough’ as reef habitat. For reefs named Asilomar, Cypress Point, Portuguese Ledge, and Point Joe only a portion of the reefs were mapped at the 2 m resolution, therefore to identify the remaining reef, we used either a 5 m resolution VRM dataset, where the VRM cutoff was greater than 0.001 (Young et al. 2010). For all reefs derived from either 2 m, 3 m or 5 m resolution, we applied a 5 m buffer around each reef habitat for potential error in positional accuracy and all reefs with an area greater than or equal to 100 m2 were included. We identified seven reefs outside of the 2 m layer that contained a significant number of CPFV points, which we decided to include in the indices. Big Reef, Blunts Reef, Isle of St. James, Point Sur Deep, Sandhill Ledge, portions of San Gregario and Soap Bank reefs were located just outside of 2 m, 3 m and 5 m ‘footprint’, therefore for these reefs we used the 2005 Habitat Suitability Probability (HSP) geodatabase for China rockfish (NMFS 2005). The HSP is a modeled output from Essential Fish Habitat geodatabase and is based upon habitat data, depth, and location, where input data are NMFS trawl datasets. In order to identify reef habitats from the Oregon border to Washington, we used a lithology shapefile (Goldfinger et al. 2014) that was based upon multiple seafloor mapping surveys including multibeam and sidescan sonar, sediment grab and core samples, and images. Seafloor types were classified according to established classification schemes (Greene et al. 1999). We considered the following lithology types as ‘reef habitat:’ Boulder, cobble, cobble mix, hard, rock, and rock mix. All spatial data was projected to NAD 1983 UTM Zone 10. Reef systems were grouped and stratified by depth at a spatial scale biologically meaningful to China rockfish. China rockfish are typically sedentary and have high site fidelity, therefore we grouped reefs in consideration of how a China rockfish would experience its surroundings. Lea (1999) recaptured China rockfish in the same general location as where they were released, however a few individuals of other rockfish species (copper (Sebastes caurinus), gopher (Sebastes carnatus), olive (Sebastes serranoides) and yellowtail (Sebastes flavidus)) demonstrated movement up to 1.5 nautical miles (about 2,700 m), but all were captured within the same reef system. In the Puget Sound copper, brown and quillback were found to have a home range less than 30m2 in high relief rocky areas (Matthews 1990). In other rockfish movement studies, China rockfish were tagged but never recaptured, or there was a F-1 sample size of 1 (Hannah and Rankin 2011), Hannah 2012). Using this limited information, we considered that China rockfish would swim no more than 200 m over smooth, sand, or muddy habitat to a neighboring reef, therefore if a reef was greater than ~200 m from rocky reef habitat it was considered a different reef system. If a reef system has contiguous habitat (no channels greater than 200 m) it remained intact, no matter how large the reef (Figures F1 and F2). A small number of reefs were merged into ‘super reefs’ to accommodate 1980s1990s CDFW location codes that overlapped multiple reefs [. Reef areas were calculated using the zonal stats tool in ArcGIS, stratified by the depth bins 0-19 m, 20-39 m, 40-59 m, 60-79 m, 80-99 m and greater than 100 m using the CSMP depth raster (2 m, 3 m or 5 m resolution). To get depths for those reefs outside the CSMP ‘footprint’ we used the NOAA Coastal Relief Model raster dataset (90 m) for California, and 100 m digital elevation model (DEM) bathymetry from the Active Tectonics and Seafloor Mapping Lab for Oregon.



Regions were designated to gain appropriate sample sizes needed for modelling. For Oregon, region differences north and south of Florence were explored. In California, 12 regions north of Pt. Conception were defined as follows: Region 1: Pt. Conception to Pt. Arguello Region 2: Purisima Point to Pt. Sal Region 3: San Luis Obispo Bay to Mill Creek (39.959◦ N) Region 4: Lopez Point to Monterey Peninsula Region 5: Moss Landing to San Francisco Bay Region 6: Farallon Islands Region 7: Point Bonita to Drakes Bay Region 8: Point Reyes to Point Arena Region 9: Point Arena to south of Ten Mile River Region 10: north of Ten Mile River to Cape Mendocino (40.16667◦ N) Region 11: Cape Mendocino to Eel River Region 12: Trinidad Head to CA/OR border CPFV drift selection During the 1987-1998 CDFW onboard observer program, fishing location was recorded as one of 459 location codes. When available, the observer also recorded coordinates, either latitude/longitude or Loran. The SWFSC converted all Loran coordinates to latitude/longitude. Using the fishing stops with available coordinates, we assigned a fishing location code to a reef. A handful of fishing location codes were obviously not associated with a reef, or a reef as identified in the above methods, and were not selected in the final dataset. If the coordinates spanned two reefs and we were unable to tell which reef F-3 was consistently fished for a given location code, we created aggregated the reefs. This most commonly occurred around the Monterey Bay peninsula. This was necessary as two-thirds of the fishing stops encountering China rockfish had no recorded coordinates and allowed us to retain all fishing location data. Therefore, for the 1987-1998 CDFW data, any fishing location that was assigned to a reef was included in the analyses as one of the filters applied to the data. For each CPFV location in the California 1999-2014 and Oregon 2001-2014 data we calculated depth, nearest reef, distance from reef, nearest MPA, distance from MPA using ArcGIS. Geoprocessing steps used were ‘near’ and ‘extract values to points.’ For consistency across databases, we used the starting location of the drift to determine if the drift was targeting fish associated with a reef. Drifts that had a distance of 0 m, i.e., were fishing directly on the reef, were included in analyses. Recognizing that some drifts begin adjacent to a reef with the intention of drifting on to the reef, as well as the fact that the starting location may not be recorded at the very start of a drift, we devised a method for including drifts within a certain distance of a reef. We compiled a list of rockfish species that are strictly reef associated (black and yellow rockfish (Sebastes chrysomelas), canary rockfish (Sebastes pinniger), China rockfish (Sebastes nebulosus), cowcod (Sebastes levis), flag rockfish (Sebastes rubrivinctus), gopher rockfish (Sebastes carnatus), grass rockfish (Sebastes rastrelliger), greenblotched rockfish (Sebastes rosenblatti), kelp rockfish (Sebastes atrovirens), quillback rockfish (Sebastes maliger), rosy rockfish (Sebastes rosaceus), starry rockfish (Sebastes constellatus), Treefish (Sebastes serriceps), vermilion rockfish (Sebastes miniatus), yelloweye rockfish (Sebastes ruberrimus)) (personal communication John Field and Tom Laidig, NMFS SWFSC). Using drifts that were greater than 0m from a reef and encountered one at least one of the fifteen species listed above, we calculated the depth for which 75% of the drifts were included. For Oregon this was 83 m, and for California it was 34 m for drifts within the ‘footprint’ and 141 m for drifts outside the ‘footprint.’ Any drift (with or without catch) greater than 83 m from a reef was excluded from the analyses.




Results
============


Discussion
==========

Recent studies have identified the need to investigate the assumptions and uncertainty in relative indices of abundance from visual surveys (Bacheler and Shertzer 2015, Campbell et al. 2015, Schobernd et al. 2013) and simulation studies (Siegfried et al. 2016).

Linear relationship between density from SCUBA surveys and a fishery-independent survey for rockfish when in the species preferred habitat and gear (Haggarty and King 2006) and for the more abundance species (Richards and Schnute 1986). 


Magnusson and Hilborn 2007 - prioritize data for stock assessments

Stock synthesis weighting of indices based on CVs - is the CV tighter for the fishery-independent survey to give it have an edge over the onboard observer survey?

Starr et al. [-@Starr2010] compared SCUBA methods to commercial fishing gear, but only sampled for two year.


CDFW sampler manual - “10 anglers should be the target number of observed anglers”



Survey indices can be either absolute or relative.  In the case of an absolute index of abundance, the entire population within the sampling area is accounted for and the index also provides information on the density of the fish species within that area  as well as aid in scaling the population size within the stock assessment model.  Most indices of abundance are relative due to the fact that the entire population within the survey area was not observed.  Estimates of absolute abundance are difficult to obtain, especially for cryptic rockfishes.  The cowcod (Sebastes levis) stock assessments is one of the only West Coast stock assessments that has incorporated an estimate of absolute abundance, derived from a visual survey (Piner et al. 2005).  The majority of stock assessments include one or more index of relative abundance.   








References {#references .unnumbered}
==========
